### ISSUE TITLE
Unable to detect multiple fields on a single line; e.g. struct{a, b int32}

### ISSUE THREAD

**Issue by mewmew** [tyranron/golang-sizeof.tips#1]
Fun project idea :)

[Here](http://golang-sizeof.tips/?t=Ly8gU2FtcGxlIGNvZGUKc3RydWN0IHsKCWEgc3RyaW5nCgliLCBkIGludDMyCgljIHN0cmluZwp9Cg==) is an example which is incorrectly parsed:

``` go
// Sample code
struct {
    a string
    b, d int32
    c string
}
```

**Comment by tyranron** [comment]
Woops! Thanks!
Didn't even think about them. Will fix in couple of days.

**Comment by mewmew** [comment]
> Woops! Thanks!
> Didn't even think about them. Will fix in couple of days.

Any updates since last time? : )

**Comment by mewmew** [comment]
Close the issue for now as it has remained inactive for more than 6 months.

Anyone with more insight into the current status may re-open the issue or add a comment about the current progress.
